name: JBoss 6 Plugin
description: The JBoss 6 plugin will allow you to interact with the JBoss server performing and undoing deployments.
version: 1.0
icon: https://cdn.jsdelivr.net/gh/clarive/cla-jboss6-plugin@master/public/icon/jboss6.svg?sanitize=true
url: https://github.com/clarive/cla-jboss6-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-jboss6-plugin
